language: android
sudo: required
jdk: oraclejdk8

notifications:
  email:
    on_success: change
    on_failure: change

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

env:
  global:
    - JAVA7_HOME=/usr/lib/jvm/java-7-oracle
    - JAVA8_HOME=/usr/lib/jvm/java-8-oracle
    - JAVA_HOME=$JAVA8_HOME
    - API=22 # Android API level by default
    - TAG=google_apis # Google APIs by default, alternatively use default
    - ABI=armeabi-v7a
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ANDROID_HOME/tools/lib
    - PATH=$ANDROID_HOME/emulator:$PATH

android:
  components:
    - tools
    - build-tools-26.0.2
    - platform-tools
    - tools

install:
  - echo yes | sdkmanager "build-tools;26.0.2" > /dev/null
  - echo yes | sdkmanager "platforms;android-26" > /dev/null

script:
  - ./gradlew check build -PdisablePreDex --continue --stacktrace